// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBO6C3Jh5u4h6PdHPsRse7TiuI2rdvdFs',
    appId: '1:283561677269:web:59add0531841b676946d5c',
    messagingSenderId: '283561677269',
    projectId: 'qaree-3d7b9',
    authDomain: 'qaree-3d7b9.firebaseapp.com',
    storageBucket: 'qaree-3d7b9.appspot.com',
    measurementId: 'G-765DT5TY2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4SZic1lddr-TmM4PBNi4LcjlmdZ1eyUo',
    appId: '1:283561677269:android:e8355da381fccf20946d5c',
    messagingSenderId: '283561677269',
    projectId: 'qaree-3d7b9',
    storageBucket: 'qaree-3d7b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnGOwfCJHS3n7UJf087Q1RvU_KOdlklNI',
    appId: '1:283561677269:ios:8c258f20426aa90c946d5c',
    messagingSenderId: '283561677269',
    projectId: 'qaree-3d7b9',
    storageBucket: 'qaree-3d7b9.appspot.com',
    iosClientId:
        '283561677269-m0j5gmr2l9gt7a3ic6nutggktevjhbin.apps.googleusercontent.com',
    iosBundleId: 'com.example.Qaree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnGOwfCJHS3n7UJf087Q1RvU_KOdlklNI',
    appId: '1:283561677269:ios:8c258f20426aa90c946d5c',
    messagingSenderId: '283561677269',
    projectId: 'qaree-3d7b9',
    storageBucket: 'qaree-3d7b9.appspot.com',
    iosClientId:
        '283561677269-m0j5gmr2l9gt7a3ic6nutggktevjhbin.apps.googleusercontent.com',
    iosBundleId: 'com.example.Qaree',
  );
}
